# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DissectAndDissolveOverlaps
                                 A QGIS plugin
 Detect, zoom to, dissect and dissolve overlaps in one polygon layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-07-02
        copyright            : (C) 2022 by Antonio Sobral Almeida
        email                : 66124.almeida@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Antonio Sobral Almeida'
__date__ = '2022-07-02'
__copyright__ = '(C) 2022 by Antonio Sobral Almeida'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DissectAndDissolveOverlaps class from file DissectAndDissolveOverlaps.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dissect_dissolve_overlaps import DissectAndDissolveOverlapsPlugin
    return DissectAndDissolveOverlapsPlugin()
